apiVersion: apps/v1
kind: Deployment
metadata:
  name: giacomo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giacomo-api
  template:
    metadata:
      labels:
        app: giacomo-api
    spec:
      containers:
        - name: giacomo-api
        # The image is a prebuilt file containing the operating system
          image: us-docker.pkg.dev/applied-honor-416721/giacomo-api/api-tests
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10